// Generated by CoffeeScript 1.7.1
(function() {
  var execute;

  window.PATH = {
    BASEURL: '/themes/resource/js/'
  };

  require.config({
    baseUrl: window.PATH.BASEURL,
    shim: {
      bootstrap: {
        deps: ['backbone']
      }
    },
    paths: {
      bootstrap: 'bootstrap/js/bootstrap'
    }
  });

  require(['bootstrap'], function(bootstrap) {
    return execute(Backbone);
  });

  execute = function(Backbone) {
    return $('#submit').on('click', function(e) {
      return $.post('/index.php?app=appointment&act=save', $('#info_table').find('input,textarea,select').serializeArray(), function(d) {
        if (d >= 0) {
          return alert('保存成功！');
        }
      });
    });
  };

}).call(this);
