// Generated by CoffeeScript 1.7.1
(function() {
  var execute;

  window.PATH = {
    BASEURL: '/themes/resource/js/'
  };

  require.config({
    baseUrl: window.PATH.BASEURL,
    shim: {
      bootstrap: {
        deps: ['backbone']
      }
    },
    paths: {
      bootstrap: 'bootstrap/js/bootstrap'
    }
  });

  require(['bootstrap'], function(bootstrap) {
    return execute(Backbone);
  });

  execute = function(Backbone) {
    return $('body').on('click', 'a.remove-item', function(e) {
      var $li, $this, $title;
      $this = $(this);
      $li = $this.parents('li.item').eq(0);
      $title = $li.find('a.txt').text();
      if (confirm('您确定要删除' + $title + '吗？')) {
        return $.post('/index.php?app=bzhwj_user_appointment&act=remove', {
          store_id: $this.attr('store_id'),
          goods_id: $this.attr('goods_id')
        }, function(d) {
          if (d >= 0) {
            return $li.remove();
          } else {
            return alert('系统错误，请联系网站管理员！');
          }
        });
      }
    });
  };

}).call(this);
